### ISSUE TITLE
pressure events

### ISSUE THREAD

**Issue by autolog** [GledholtHall/beta-3#4]
Pressure works which is great but the topic name is inconsistent with other measurements.
The others seem to start with "measure-.....", "pressure" is just "pressure" i.e.:
![pressure](https://user-images.githubusercontent.com/11138074/108523163-83c85480-72c5-11eb-88f4-653e6afec95c.png)

**Comment by xAPPO** [comment]
I'm a bit unsure on which is better - I was thinking of removing measure- from the others.  I originally included it to be compatible with the Athom Homey homie implementation.   Having both is obviously wrong.

**Comment by autolog** [comment]
I would be happy with measure- prefix being removed :)

**Comment by dgz** [comment]
The measure- prefix implies that the property is not settable but there is a $settable property attribute that actually defines it. 
The [homie spec](https://homieiot.github.io/specification/#node-attributes) gives "temperature" (without the measure- prefix) as an example but they don't define valid property names which is doesn't make one way or the other absolutely correct. 
I think measure- is unnecessary given the $settable attribute that clearly defines settable or not and makes the term "measure" irrelevant.

**Comment by xAPPO** [comment]
I agree that measure- is redundant because of $settable and in fact I favour removing it just for tidiness plus it probably should appear elsewhere in topics too.  It will require matching two payload values for a device which is not as simple as it appears though. 

The measure- usage originated because it's a Homey capability name and in that implementation I think these capabilities/attributes were just pushed to homie 'as is' .  This made it easier to read in value from homie to update attributes too as no lookup or mapping was needed.  But I do feel it's a case of just who used homie first and dropping measure is more generic.
