### ISSUE TITLE
Error setting dim value on TRV

### ISSUE THREAD

**Issue by autolog** [GledholtHall/beta-3#7]
I am testing a Aeotec/Eurotronic Z-Wave TRV.

I am using this driver: [eTRV Aeotec Radiator Thermostat and Eurotronic Spirit Z-Wave Thermostats](https://community.hubitat.com/t/etrv-aeotec-radiator-thermostat-and-eurotronic-spirit-z-wave-thermostats/48935)

The TRV device looks like this: 
![trv_device_1](https://user-images.githubusercontent.com/11138074/110247118-80d69080-7f62-11eb-889d-9f07941c4a5a.png)
![trv_device_2](https://user-images.githubusercontent.com/11138074/110247121-83d18100-7f62-11eb-800a-775179145c63.png)

MQTT Explorer looks like this:
![trv_mqtt_explorer](https://user-images.githubusercontent.com/11138074/110247129-921f9d00-7f62-11eb-9dc7-6582b74e6ebb.png)

When I publish a set for the dim value, I am getting this error:
<img width="1131" alt="trv_dim_error" src="https://user-images.githubusercontent.com/11138074/110247145-a95e8a80-7f62-11eb-8d49-e20abd95cc37.png">

Now, I can't be sure but I think this was working and isn't now?

Posting here first as I am not sure if it is an issue with the MQTT App or the TRV driver.

**Comment by GledholtHall** [comment]
This error is in the driver code (dev313)  is I think happening because the Dim setLevel() takes two parameters.  The level requested and the duration in seconds over which to implement the change..   I am guessing the setLevel() command as implemented in this driver does not use or handle the second parameter.  The easiest and most compatible fix would be for a suitable command to be added to the driver code (just ignoring the second parameter)  but I'll take a look too.

**Comment by baku104788** [comment]
I disagree - this is not an error in the driver.  The requirement to have a duration of the level change is mostly specific to lighting.  Other capabilities incorporate a set level command without a duration. (An audio device for example). This heating device should not require a duration for a level change.

**Comment by GledholtHall** [comment]
The error IS thrown in the driver - that's what I was saying. I do understand your point but it's awkward to fix at the senders end when your not using a specific TRV capability (because there isn't one)

Capability SwitchLevel has a command as follows - 

``
SwitchLevel
Device Selector

capability.switchLevel
Driver Definition

capability "SwitchLevel"
Attributes

level - NUMBER
Commands

setLevel(level, duration)
level required (NUMBER) - Level to set (0 to 100)
duration optional (NUMBER) - Transition duration in seconds
```


it 'supports a second optional parameter and the driver should help by accepting this but ignoring   
`define setLevel (level, duration=null)`
 and that way it just works.   If you have to check manually whether every command you send with an optional parameter fails or not to an unknown device then you have to trap errors in every single call to an **external** driver. There are hundreds of such calls in MQTT

setLevel when implemented in a MusicPlayer Device does not offer a second optional parameter

**Comment by GledholtHall** [comment]
OTOH I may be able to arrange that when no duration has been set via MQTT (as in this case) then that parameter is not sent in the call.   This will set the duration to the default implemented by the device driver rather than the current '1' which is applied to all dimmable devices for consistency.
